runmodel="test"

apiVersion = "v1"
port = "8080"

[log]
logPath = "/home/root/tmp/log"
logFileName = "application.log"
printConsole = true
maxNumber = 10
maxSize = 2
# 1:debug
level = 1

[database]
db_host = "localhost"
db_port = 3306
db_user = "yygcmsg"
db_pass = "yygcmsg"
db_name = "yygcmsg"
db_type = "mysql"
